print("Please enter the number of lives.")
Lives = int(input())
print()
print("Please enter the energy level.")
elvl = int(input())
print() 
print("Please enter the shield level.")
slvl = int(input())
print()
print("Health has been set.")
print()
print(" Lives: " + Lives*('♥'))
print("Energy: " + elvl*('♦'))
print("Shield: " + slvl*('♦'))